version: '3'
services:
  postgres:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: covars_clim_soil
    ports:
      - "5434:5432"  # Changed from 5432:5432 to avoid port conflict
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: